# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('begin_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygoals.Goal'),
        ),
    ]
