# Generated by Django 2.0 on 2018-12-24 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('load_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('begin_value', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('last_plot_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('plotly_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygoals.Goal'),
        ),
    ]
