# Generated by Django 2.0 on 2018-12-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='plot_html',
            field=models.TextField(default='Warning: Plot missing!'),
        ),
    ]
