# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoals', '0002_auto_20161223_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='event_dt',
        ),
        migrations.AddField(
            model_name='event',
            name='load_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_plot_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='plotly_url',
            field=models.CharField(default='noplotlyurl', max_length=100),
            preserve_default=False,
        ),
    ]
