# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygoals', '0003_auto_20161225_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='load_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goal',
            name='last_plot_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
