# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoals', '0004_auto_20161225_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='plotly_url_large',
            field=models.CharField(default='nographyet', max_length=100),
            preserve_default=False,
        ),
    ]
